//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStockManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shareholder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shareholder()
        {
            this.Stock_Account = new HashSet<Stock_Account>();
        }
    
        public string ID { get; set; }
        public Nullable<float> Total_Shares { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public string CompanyID { get; set; }
        public string Shareholder_TypeID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User_Account User_Account { get; set; }
        public virtual Shareholder_Type Shareholder_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_Account> Stock_Account { get; set; }
    }
}
