//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStockManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock_Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public string ID { get; set; }
        public string Status { get; set; }
        public string Shares_Type { get; set; }
        public Nullable<float> Current_Amount { get; set; }
        public string Beneficiary { get; set; }
        public Nullable<System.DateTime> Expired_Date { get; set; }
        public string ShareholderID { get; set; }
        public string Share_TypeID { get; set; }
    
        public virtual Shareholder Shareholder { get; set; }
        public virtual Shares_Type Shares_Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
