//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStockManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> Transaction_Time { get; set; }
        public string Status { get; set; }
        public Nullable<float> Shares_Quantity { get; set; }
        public Nullable<System.DateTime> Time_Approve { get; set; }
        public string SeriesID { get; set; }
        public string Stock_AccountID { get; set; }
        public string Transaction_TypeID { get; set; }
    
        public virtual Series Series { get; set; }
        public virtual Stock_Account Stock_Account { get; set; }
        public virtual Transaction_Type Transaction_Type { get; set; }
    }
}
